[package]
name = "src"
version = "1.3.0"
cairo-version = "2.5.3"

[tool.NodeGuardians]
part_1 = "The Hall of Immutability"
part_2 = "The Sanctuary of Constants"
part_3 = "The Realm of Shadows"

# See more keys and their definitions at https://docs.swmansion.com/scarb/docs/reference/manifest